config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/set', to: 'goalposts#new'
  post '/set', to: 'goalposts#create'
  get 'rakuten_search' => 'goalposts#form'
  resources :users
  resources :goalposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goalpost.rb
class Goalpost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :from, presence: true, length: { maximum: 140 }

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/goalposts_controller.rb
class GoalpostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy, :update, :show, :new, :edit]
    before_action :correct_user,   only: [:destroy, :update]

    def new
        @goalpost = current_user.goalposts.build if logged_in?
        if params[:keyword]
            @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
        end
        @i = 0
    end

    def show
        @goalpost = Goalpost.find(params[:id])
        @likes = Like.where(goalpost_id: params[:goalpost_id])
        @comment = Comment.new
        @comments = @goalpost.comments
        @item = RakutenWebService::Ichiba::Item.search(itemCode: @goalpost.reward)
    end

    def create
        @goalpost = current_user.goalposts.build(goalpost_params)
        if @goalpost.save
            flash[:success] = "目標を設定しました"
            redirect_to current_user
        else
            @feed_items = []
            redirect_to '/set'
        end
    end

    def edit
        @goalpost = Goalpost.find(params[:id])
        if params[:keyword]
            @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
        end
        @i = 0
    end

    def update
        @goalpost = Goalpost.find(params[:id])
        if @goalpost.update_attributes(goalpost_params)
            flash[:success] = "プロフィールを変更しました"
            redirect_to @goalpost
        else
            render 'edit'
        end
    end

    def destroy
        @goalpost.destroy
        flash[:success] = "目標が削除されました"
        redirect_to current_user
    end

    def form
        if params[:keyword]
          @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
        end
    end

    private

    def goalpost_params
      params.require(:goalpost).permit(:from, :to, :goal, :comment, :reward)
    end

    def correct_user
        @goalpost = current_user.goalposts.find_by(id: params[:id])
        redirect_to current_user if @goalpost.nil?
      end
end

app/helpers/goalposts_helper.rb
module GoalpostsHelper
    # def  time_left(goalpost)
    #     from = goalpost.from.delete("-").to_i
    #     to = goalpost.to.delete("-").to_i
    #     today = Date.today.strftime("%Y%m%d").to_i
    #     check = to-today
    #     if today >= from
    #       if check <= 0
    #         @time_left = "終了しています"
    #       else
    #         @time_left = "残り#{to-today}日"
    #       end
    #     else
    #       @time_left = "#{from - today}日後開始" 
    #     end
    # end

    def  time_left(goalpost)
      from = Date.parse(goalpost.from)
      to = Date.parse(goalpost.to)
      today = Date.today
      check = (to-today).to_i
      if today.strftime("%Y%m%d") >= from.strftime("%Y%m%d")
        if check <= 0
          @time_left = "終了しています"
        else
          @time_left = "残り#{(to-today).to_i}日"
        end
      else
        @time_left = "#{(from - today).to_i}日後開始" 
      end
  end
end

app/views/goalposts/_form.html.erb
<div class="py-5 text-center" >
<div class="row py-5" style="display:block;">
<p class="close-btn right">✖︎</p>
<div class="mx-auto col-md-6 col-10 py-5 box" style="">    
  <%= form_tag({action: 'new'}, method: :get, remote: true) do %>
  <%= label_tag :keyword, 'キーワード検索' %>
  <%= text_field_tag 'keyword', params[:keyword] %>
</div>
<%= submit_tag "検索", {id: 'search', class: 'btn btn-primary clearfix'} %>
  <% end %>

</div>
</div>

app/views/goalposts/_form.js.erb
$('#result').html("<%= escape_javascript(render 'search_result') %>");

$(".close-btn").click(function(){
    $("#search_result").fadeOut("slow");
    //背景固定を解除する
    releaseScrolling();    
});

//背景固定解除
function releaseScrolling(){
    $('html').css({
        'position': 'relative',
        'width': '',
        'top': ''
    });
    $(window).scrollTop(pointY);
}

app/views/goalposts/_goalpost.html.erb
<% @item = RakutenWebService::Ichiba::Item.search(itemCode: goalpost.reward) %>
  <% @item.each do |item| %>
    <div class="col-md-6 col-lg-3">     
      <div class="mb-4 text-dark Box g-Box" style="text-decoration: none;">
        <%= link_to "", "/goalposts/#{goalpost.id}", method: :get %>
        <img class="pt-4" src="<%= item['mediumImageUrls'][0] %>"> 
        <div class="item-box pt-4">
          <div class="pt-1" style="width: 100%">
            <%= goalpost.goal %>            
          </div>
          <div class="pt-1 <%= 'text-danger' if time_left(goalpost) == "残り1日" %>">
            <%= time_left(goalpost) %>
          </div>
          <div class="pt-1">
            <%= image_tag("icon_heart.png", class:"pb-1")  %>
            <%= goalpost.likes_count %>           
          </div>
        </div>
      </div>      
    </div>
<% end %>

app/views/goalposts/_goalpost_feed.html.erb
<% @item = RakutenWebService::Ichiba::Item.search(itemCode: goalpost.reward) %>
  <% @item.each do |item| %>
    <div class="col-md-4 col-lg-2">     
      <div class="mb-4 text-dark Box g-Box" style="text-decoration: none;">
        <%= link_to "", "/goalposts/#{goalpost.id}", method: :get %>
        <img class="pt-2" style="width: 90px; height: 90px; object-fit: contain;" src="<%= item['mediumImageUrls'][0] %>"> 
        <div class="item-box pt-2">
          <div class="pt-1 px-1 text-left" style="height: 3rem; display:inline-block;">
            <%= goalpost.goal %>            
          </div>
          <div class="pt-1 <%= 'text-danger' if time_left(goalpost) == "残り1日" %>">
            <%= time_left(goalpost) %>
          </div>
          <div class="pt-1">
            <%= image_tag("icon_heart.png", class:"pb-1")  %>
            <%= goalpost.likes_count %>           
          </div>
        </div>
      </div>      
    </div>
<% end %>

app/views/goalposts/_goalpost_like.html.erb
<% @like.each do |like| %>
    <% @goalpost = Goalpost.find(like.goalpost_id) %>
    <%= render @goalpost %>
<% end %>

app/views/goalposts/_search_result.html.erb
<div class="py-5 text-center">
<div class="row" style="display:block;">
<p class="close-btn right">✖︎</p>
<div class="mx-auto col-lg-6 box" style="height: 80vh;">

<div class="py-3 text-center" >
    <div class="container">
      <div class="row">
        <% if @items.present? %>
        <% @items.each do |item| %>
        
        <input type="radio" name="item_box" item_name="<%= item.name %>" value="<%= item['itemCode'] %>" id="<%= @i %>">
        
        <label for="<%= @i %>" class="col-lg-3 col-md-3 p-4">
            <img class="" src="<%= item['smallImageUrls'][0] %>">
            <div style="width: 100%">
                <p class="mb-1" id="item_name"><%= item.name %></p>
            </div>
            <p class="mb-0"><%= number_with_delimiter(item.price) %>円</p>
        </label>
        
        
        <% @i+=1 %>
        <% end %>
        <% end %> 
      </div>     
    </div>    
  </div>
</div>
<a id= 'search' class= 'btn btn-primary clearfix check'>選択する</a>
</div>
</div>

app/views/goalposts/edit.html.erb
  <% provide(:title, "目標編集画面") %>
<% breadcrumb :edit_goalpost, @goalpost %>
  
  <div class="py-5 text-center" >
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="section-title">
            <h3>目標編集</h3>
            <hr>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="mx-auto col-lg-6 col-10" style="">
          <div class="text-left">
            <%= form_for(@goalpost) do |f| %>
              <div class="form-group">
                <%= f.label :from, "いつから？" %>
                <%= f.date_field :from, class: "form-control", id: "form16" %>
              </div>
              <div class="form-group"> 
                <%= f.label :to, "いつまでに？"%>
                <%= f.date_field :to, class: "form-control", id: "form17" %>
              </div>
              <div class="form-group">
                <%= f.label :goal, "何をしますか？"%>
                <%= f.text_field :goal, class: "form-control", id: "form18", placeholder: "数学の宿題を終わらせる" %>   
              </div>
              <div class="form-row">
                <div class="form-group col-md-12" style=""> <label for="form20">ごほうびを選びましょう</label>
                  <div class="input-group">
                    <div class="input-group-append">
                      <div>
                      <button class="btn btn-primary" id= "r_select" type="button">楽天で検索</button>
                      </div>
                      <div id="check_result"></div>
                      <%= f.hidden_field :reward, id: "reward" %>
                    </div>                    
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :comment, "コメント" %>
                <%= f.text_area :comment, class: "form-control", id: "form21", placeholder: "数学の宿題を終わらせる" %>   
              </div>
          </div>
          <div class="py-3">
            <%= f.submit "編集する", class: "btn w-50", style: "background-color: sandybrown" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<div id="form">
<%= render 'form' %>
</div>
<div id="search_result">
<div id="result"></div>
</div>

app/views/goalposts/form.html.erb
<%= render 'form' %>

app/views/goalposts/new.html.erb
  <div class="py-5 text-center" >
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="section-title">
            <h3>目標設定</h3>
            <hr>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="mx-auto col-lg-6 col-10" style="">
          <div class="text-left">
            <%= form_for(@goalpost) do |f| %>
              <div class="form-group">
                <%= f.label :from, "いつから？" %>
                <%= f.date_field :from, class: "form-control", id: "form16", placeholder:"例:2018-02-01" %>
              </div>
              <div class="form-group"> 
                <%= f.label :to, "いつまでに？"%>
                <%= f.date_field :to, class: "form-control", id: "form17", placeholder:"例:2018-02-08" %>
              </div>
              <div class="form-group">
                <%= f.label :goal, "何をしますか？"%>
                <%= f.text_field :goal, class: "form-control", id: "form18", placeholder: "数学の宿題を終わらせる" %>   
              </div>
              <div class="form-row">
                <div class="form-group col-md-12" style=""> <label for="form20">ごほうびを選びましょう</label>
                  <div class="input-group">
                    <div class="input-group-append">
                      <div>
                      <button class="btn btn-primary" id= "r_select" type="button">楽天で検索</button>
                      </div>
                      <div id="check_result"></div>
                      <%= f.hidden_field :reward, id: "reward" %>
                    </div>                    
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :comment, "コメント" %>
                <%= f.text_area :comment, class: "form-control", id: "form21", placeholder: "テスト前なので頑張ります！" %>   
              </div>
          </div>
          <div class="py-3">
            <%= f.submit "投稿する", class: "btn w-50", style: "background-color: sandybrown" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<div id="form">
<%= render 'form' %>
</div>
<div id="search_result">
<div id="result"></div>
</div>

app/views/goalposts/new.js.erb
$('#result').html("<%= escape_javascript(render 'search_result') %>");

$(".close-btn").click(function(){
    $("#search_result").fadeOut("slow");
    //背景固定を解除する
    releaseScrolling();       
});

$(".check").click(function(){
    name = $('input[type="radio"]:checked').attr('item_name');
    value = $('input[type="radio"]:checked').val();
    $("#check_result").html(name);
    $("#reward").val(value);
    $("#search_result").fadeOut("slow");
    //背景固定を解除する
    releaseScrolling();       
});

//背景固定解除
function releaseScrolling(){
    $('html').css({
        'position': 'relative',
        'width': '',
        'top': ''
    });
    $(window).scrollTop(pointY);
}

app/views/goalposts/result.html.erb
<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th>画像</th>
    </tr>
  </thead>
  <tbody>
  <% if @items.present? %>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, "#{item.url}" %></td>
        <td align="right"><%= number_with_delimiter(item.price) %>円</td>
        <td><img src="<%= item['smallImageUrls'][0] %>"></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/goalposts/search.html.erb
<%= render 'form', items: @items %>

app/views/goalposts/show.html.erb
<% provide(:title, "目標画面") %>
<% breadcrumb :goalpost, @goalpost %>

<div class="position-fixed r-32 b-32" style="z-index: 10;">
    <div class="container">
      <div class="row">
        <div class="col-md-12 Box btn btn-dark btn-lg">
          <%= link_to "", "/set", method: :get %>
          <div>
            <p style="font-size: 16px;">目標を設定する</p>
            <%= fa_icon("calendar 3x") %>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="pb-5">
    <div class="container text-center">
        <div class="row border mx-auto mb-3 bgc-w" style="width: 750px; border-radius: 8px;">
            <div class="text-center mx-auto col-lg-10">
                <div class="section-title py-3">
                    <h3><%= @goalpost.goal %></h3>
                    <hr>
                </div>
                <div class="mx-auto pb-2">
                <% @item.each do |item| %>
                    <div class="row">
                        <div class="col-lg-3 col-md-3 pr-0">
                            <img class="align-middle" style="width: 90px; height: 90px; object-fit: contain;" src="<%= item['mediumImageUrls'][0] %>"> 
                             <div class="pt-3 <%= 'text-danger' if time_left(@goalpost) == "残り1日" %>">
                            <%= time_left(@goalpost) %>
                            </div>
                            <div class="pt-2">
                            <%= render partial: 'likes/like', locals: { goalpost: @goalpost, likes: @likes } %>
                            </div>
    
                        </div>
                        <div class="col-lg-9 col-md-9">

                        <table class="table table-bordered" style="table-layout:fixed; font-size:13px;">
                            <tbody class="text-left g-tbody">
                                <tr>
                                <th class="align-middle" style="width: 100px;">投稿者</th>
                                <td><%= link_to @goalpost.user.name, @goalpost.user %></td>
                                </tr>
                                <tr>
                                <th class="align-middle">ごほうび</th>
                                <td><%= link_to item.name, "#{item.url}" %></td>
                                </tr>
                                <tr>
                                <th class="align-middle">意気込み</th>
                                <td><%= simple_format(@goalpost.comment, class:"mb-0") %></td>
                                </tr>
                            </tbody>
                         </table>
                        </div>
                    </div>
                <% end %>
                </div>

            </div>
        </div>
        <div class="row border mx-auto mb-3 bgc-w" style="width: 750px; border-radius: 8px;">
            <% if current_user?(@goalpost.user) %>
                <div class="text-center mx-auto col-lg-12">
                    <%= link_to "目標の編集", edit_goalpost_path(@goalpost), class: "btn btn-a btn-lg my-2", style:"width: 90%; font-size: 14px; background-color: #fcac45;", method: :get %>
                    <%= link_to "この目標を削除する", @goalpost, method: :delete,
                                                    data: { confirm: "本当に削除しますか?" }, class: "btn btn-a btn-lg my-2", style:"width: 90%; font-size: 14px;" %>   
                </div>
            <% end %> 
        </div>
        <div class="row border mx-auto bgc-w" style="width: 750px; border-radius: 8px;">
            <div class="text-center px-auto col-lg-12">
                    <%= render partial: 'comments/index', locals: { comments: @comments } %>
                <% if logged_in? %>
                    <%= render partial: 'comments/form', locals: { comment: @comment, goalpost: @goalpost } %>
                <% end %>
            </div>
        </div>
    </div>
</div>