config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/set', to: 'goalposts#new'
  post '/set', to: 'goalposts#create'
  get 'rakuten_search' => 'goalposts#form'
  resources :users
  resources :goalposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :goalpost, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def create
    @like = Like.create(user_id: current_user.id, goalpost_id: params[:goalpost_id])
    @likes = Like.where(goalpost_id: params[:goalpost_id])
    @goalpost = Goalpost.find(params[:goalpost_id])
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, goalpost_id: params[:goalpost_id])
    like.destroy
    @likes = Like.where(goalpost_id: params[:goalpost_id])
    @goalpost = Goalpost.find(params[:goalpost_id])
    
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end

  end

  def set_variables
    @goalpost = Goalpost.find(params[:goalpost_id])
    @id_name = "#like-link-#{@goalpost.id}"
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.nil? %>
    <div class="btn border n-btn">
    <%= image_tag("icon_heart.png") %>
    <span>
    いいね!
    <%= goalpost.likes_count %>
    </span>
    </div>
<% else %>

    <% if goalpost.user_id != current_user.id  %>
        <div class="like-link" id="like-link-<%= goalpost.id %>">
            <% if goalpost.like_user(current_user.id) %>
            <%= button_to goalpost_like_path(likes, goalpost_id: goalpost.id), class: "like-btn", method: :delete, remote: true do %> 
                <%= image_tag("icon_red_heart.png") %>
                <span>
                いいね!
                <%= goalpost.likes_count %>
                </span>
            <% end %>
            <% else %>
            <%= button_to goalpost_likes_path(goalpost), class: "like-btn", remote: true do %>  
                <%= image_tag("icon_heart.png") %>
                <span>
                いいね!
                <%= goalpost.likes_count %>
                </span>
            <% end %>
            <% end %>
        </div>
    <% else %>
        <div class="btn border n-btn">
        <%= image_tag("icon_heart.png") %>
        <span>
        いいね!
        <%= goalpost.likes_count %>
        </span>
        </div>
    <% end %>

<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/create.js.erb
$("<%= @id_name %>").html("<%= escape_javascript(render partial: 'likes/like', locals: { goalpost: @goalpost, likes: @likes, like: @like}) %>");

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/destroy.js.erb
$("<%= @id_name %>").html("<%= escape_javascript(render partial: 'likes/like', locals: { goalpost: @goalpost, likes: @likes }) %>");