config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/set', to: 'goalposts#new'
  post '/set', to: 'goalposts#create'
  get 'rakuten_search' => 'goalposts#form'
  resources :users
  resources :goalposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer" style="background-color:white;">
    <div class="container">
      <div class="row d-flex justify-content-between my-5">
        <div class="col-md-12">
          <div class="row text-center">
            <div class="col-lg-4 col-md-4">
              <h5>Motif</h5>
              <hr>
              <ul class="list-unstyled">
                <li><%= link_to "Top", "/", class: "no-dec" %></li>
                <li><%= link_to "Motifとは", "/#about", class: "no-dec" %></li>
              </ul>
            </div>
            <div class="col-lg-4 col-md-4">
              <h5>Webmaster</h5>
              <hr>
              <ul class="list-unstyled">
                <li><%= link_to "乙村海斗", "https://k0a1i1t6o.github.io", class: "no-dec" %></li>
              </ul>
            </div>
            <div class="col-lg-4 col-md-4">
              <h5>Contact</h5>
              <hr>
              <ul class="list-unstyled">
                <li><%= link_to "お問い合せ", "mailto:kaikai25250116@gmail.com", class: "no-dec" %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-12 border-top pt-5">
          <div class="col-md-12 text-center">
            <p class="text-secondary mb-0" style="font-size: 1.5em;">Motif</p>
          </div>
          <div class="col-md-12 text-center">
            <p class="text-secondary mb-0">© 2019 Kaito Otsumura</p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light py-0 header">
    <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#inv-bar" style="outline:none;">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="text-center">
        <% if logged_in? %>
        <%= link_to "Motif", home_path, class:"text-dark", style:"text-decoration: none; font-size: 1.5em;" %>
        <% else %>
            <%= link_to "Motif", root_path, class:"text-dark", style:"text-decoration: none; font-size: 1.5em;" %>
        <% end %>
    </div>
    <div class="collapse navbar-collapse justify-content-end">
        <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li class="dropdown">
                <a href="" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    
                    <% if current_user.picture? %>
                    <%= image_tag current_user.picture.thumb30.url, style:"background-color: white;", class:"pb-1 mr-2 rounded-circle" %>
                    <% else %>
                    <%= image_tag 'no-image.png', size: '30x30', class:"mr-2 rounded-circle" %>
                    <% end %>
                    
                    <%= current_user.name %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item"> <%= link_to "マイページ", current_user, class: "nav-link" %> </li>
                    <li class="dropdown-item"> <%= link_to "プロフィールを編集", edit_user_path(current_user), class: "nav-link" %> </li>
                    <li class="dropdown-item"> <%= link_to "ログアウト", logout_path, class: "nav-link", method: :delete %> </li>
                </ul>
            </li>
        <% else %>
            <li class="nav-item"> <%= link_to "ログイン", login_path, class: "nav-link" %> </li>
            <li class="nav-item"> <%= link_to "新規登録", signup_path, class: "nav-link" %> </li>
        <% end %>
            
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= breadcrumbs separator: "  &rsaquo;  ", class:"bread" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> text-center"><%= message %><a class="close" data-dismiss="alert"> <span >×</span> </a></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
  
</html>